# Generated by Django 3.2.10 on 2022-02-09 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 14, 16, 44, 869481, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
